#!/bin/bash

export VCAP_APPLICATION='{
  "application_name": "cf-postgres-shared-broker",
  "application_version": "1.0",
  "application_uris": [
    "localhost:30003"
  ]
}'
export VCAP_SERVICES='{
  "pg-blacksmith":[
    {
      "name":"my-postgres",
      "label":"my-postgres",
      "tags": ["blacksmith","postgres","postgresql"],
      "plan": "postgres/standalone",
      "credentials": {
        "host": "10.200.204.8",
        "port": 5432,
        "username": "CMg8ASeaoG5U1RCE",
        "password": "6panlGBIlb6NQdz2QYksX4iKSOOPFxeLeWuVhGEdgQiXLg6Tvlr3Cr9sLp1TNrgX"
      }
    }
  ]
}'

export PORT=3003
./cf-postgres-shared-broker
